---

# This module is courtesy of DigiBlur, with enhancements by myself for
# packaging purposes.
# Original Source:
#   https://github.com/digiblur/digiNRG_ESPHome/WyzeOutdoorPlug/wyzeoutdoor.yaml@main
# MIT License; see original source for LICENSE information.

esphome:
  name: wyzeoutdoor2plug
  name_add_mac_suffix: true
  friendly_name: "Wyze Outdoor Smart Plug (dual)"
  project:
    name: "DigiBlur.Wyze Outdoor"
    version: "1.0"

esp32:
  board: esp-wrover-kit

dashboard_import:
  package_import_url: github://joshuaboniface/martinjerry-esphome/wyze-outdoor/wyze-outdoor.yaml

preferences:
  flash_write_interval: 15sec

substitutions:
  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "770"

logger:
  level: INFO
  baud_rate: 0

api:
  reboot_timeout: 15min

ota:
  platform: esphome

web_server:
  port: 80

captive_portal:

mdns:
  disabled: false

wifi:
  ap: {}
  domain: ""
  output_power: 8.5dB
  reboot_timeout: 15min
  power_save_mode: none

switch:
  - platform: gpio
    name: "Relay 1"
    pin:
      number: GPIO15
      inverted: false
    id: relay1
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - light.turn_on: relay1_led
    on_turn_off:
      - light.turn_off: relay1_led
  - platform: gpio
    name: "Relay 2"
    pin:
      number: GPIO32
      inverted: false
    id: relay2
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - light.turn_on: relay2_led
    on_turn_off:
      - light.turn_off: relay2_led
  - platform: restart
    name: Restart

output:
  - platform: gpio
    pin: GPIO19
    inverted: True
    id: relay1_led_gpio

  - platform: gpio
    pin: GPIO16
    inverted: True
    id: relay2_led_gpio

light:
  - platform: binary
    name: "Relay1 LED"
    id: relay1_led
    internal: true
    output: relay1_led_gpio
  - platform: binary
    name: "Relay2 LED"
    id: relay2_led
    internal: true
    output: relay2_led_gpio

sensor:
  - platform: adc
    pin: GPIO34
    name: "Light Level"
    update_interval: 10s
    attenuation: 11db
    unit_of_measurement: lux
  - platform: hlw8012
    sel_pin:
      number: GPIO25
      inverted: true
    cf_pin: GPIO27
    cf1_pin: GPIO26
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    change_mode_every: 3
    update_interval: 3s
    current:
      name: "Current"
      unit_of_measurement: A
      accuracy_decimals: 2
    voltage:
      name: "Voltage"
      unit_of_measurement: V
      accuracy_decimals: 1
    power:
      name: "Power"
      unit_of_measurement: W
      accuracy_decimals: 0
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 134 -> 58

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO18
      mode: INPUT_PULLDOWN
      inverted: True
    name: Button1
    on_press:
      - switch.toggle: relay1
  - platform: gpio
    internal: true
    pin:
      number: GPIO17
      mode: INPUT_PULLDOWN
      inverted: True
    name: Button2
    on_press:
      - switch.toggle: relay2

status_led:
  pin:
    number: GPIO5
    inverted: true
